### PR TITLE
MLSC_Candidate_Test_Ruben

### PR DESCRIPTION
**Pull request by mrubenw**
Hi Alex, I've created a Markdown file that contains the Q&A for the test. Looking forward to your feedback. Thank you. Kind regards, Ruben

### CODE REVIEW

**Comment by aershov24** [comment]
Hi Ruben. Thanks for your submission. We liked how you approached Q2 and Q3 but all three QAs were sourced from a similar website that we won't consider as a quality resource. Please resubmit your Q1 and Q3 from different sources and rewrite Q2 (for you have A, B, C on the image but referencing examples as Left, Center, Right). Thanks.

**Review by aershov24 — CHANGES_REQUESTED** [review]
Hi Ruben. Thanks for your submission. We liked how you approached Q2 and Q3 but all three QAs were sourced from a similar website that we won't consider as a quality resource. Please resubmit your Q1 and Q3 from different sources and rewrite Q2 (for you have A, B, C on the image but referencing examples as Left, Center, Right). Thanks.

**Comment by mrubenw** [comment]
Hi Alex,

Thank you very much for your feedback. Give me an hour to resubmit the
solution.
Thanks.

Regards,
Ruben

**Comment by mrubenw** [comment]
Hi Alex,

I've made some changes to the file. Kindly let me know your feedback. Thank you.

**Comment by aershov24** [comment]
Hi Ruben, we do like your work but have already filled the pool of candidates for MLSC at this stage. We will keep you in mind as a priority candidate and will contact you in no time once the opportunity will arise.

**Pull request closed without merging**
